spring:
  application:
    name: encurtador-url

server:
  port: 5050

  datasource:
    url: jdbc:postgresql://localhost:5051/db-encurtador-url
    username: user_gustavo
    password: senha_gustavo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 5053

  flyway:
    enabled: true
    locations: classpath:db/migration

  springdoc:
    swagger-ui:
      path: /swagger-ui.html # http://localhost:5050/swagger-ui.html

  jackson:
    time-zone: America/Sao_Paulo




